# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/main_main.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab, icon, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tableView_Order = QtWidgets.QTableView(self.tab_2)
        self.tableView_Order.setObjectName("tableView_Order")
        self.gridLayout_5.addWidget(self.tableView_Order, 0, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_Orders_Teerace_tb = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_Orders_Teerace_tb.setChecked(True)
        self.checkBox_Orders_Teerace_tb.setObjectName("checkBox_Orders_Teerace_tb")
        self.gridLayout.addWidget(self.checkBox_Orders_Teerace_tb, 0, 0, 1, 1)
        self.checkBox_Orders_Teerace_jd = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_Orders_Teerace_jd.setChecked(True)
        self.checkBox_Orders_Teerace_jd.setObjectName("checkBox_Orders_Teerace_jd")
        self.gridLayout.addWidget(self.checkBox_Orders_Teerace_jd, 1, 0, 1, 1)
        self.checkBox_Orders_Teerace_pdd = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_Orders_Teerace_pdd.setChecked(True)
        self.checkBox_Orders_Teerace_pdd.setObjectName("checkBox_Orders_Teerace_pdd")
        self.gridLayout.addWidget(self.checkBox_Orders_Teerace_pdd, 2, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.checkBox_Orders_Type_wait = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_Orders_Type_wait.setChecked(True)
        self.checkBox_Orders_Type_wait.setObjectName("checkBox_Orders_Type_wait")
        self.gridLayout_3.addWidget(self.checkBox_Orders_Type_wait, 0, 0, 1, 1)
        self.checkBox_Orders_Type_succe = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_Orders_Type_succe.setObjectName("checkBox_Orders_Type_succe")
        self.gridLayout_3.addWidget(self.checkBox_Orders_Type_succe, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 1, 1, 1)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../icons/main_data.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_2, icon1, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menuFile.addAction(self.actionOpen)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Main"))
        self.groupBox.setTitle(_translate("MainWindow", "订单平台"))
        self.checkBox_Orders_Teerace_tb.setText(_translate("MainWindow", "淘宝"))
        self.checkBox_Orders_Teerace_jd.setText(_translate("MainWindow", "京东"))
        self.checkBox_Orders_Teerace_pdd.setText(_translate("MainWindow", "拼多多"))
        self.groupBox_2.setTitle(_translate("MainWindow", "订单类型"))
        self.checkBox_Orders_Type_wait.setText(_translate("MainWindow", "等待收货"))
        self.checkBox_Orders_Type_succe.setText(_translate("MainWindow", "交易成功"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Orders"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))

