# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.comboBox_Order_TimeStart = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBox_Order_TimeStart.setObjectName("comboBox_Order_TimeStart")
        self.comboBox_Order_TimeStart.addItem("")
        self.comboBox_Order_TimeStart.addItem("")
        self.comboBox_Order_TimeStart.addItem("")
        self.comboBox_Order_TimeStart.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_Order_TimeStart, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_5, 0, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.comboBox_Order_TimeStop = QtWidgets.QComboBox(self.groupBox_6)
        self.comboBox_Order_TimeStop.setObjectName("comboBox_Order_TimeStop")
        self.comboBox_Order_TimeStop.addItem("")
        self.comboBox_Order_TimeStop.addItem("")
        self.comboBox_Order_TimeStop.addItem("")
        self.comboBox_Order_TimeStop.addItem("")
        self.gridLayout_7.addWidget(self.comboBox_Order_TimeStop, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_6, 0, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.comboBox_Order_TimeUnit = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_Order_TimeUnit.setObjectName("comboBox_Order_TimeUnit")
        self.comboBox_Order_TimeUnit.addItem("")
        self.comboBox_Order_TimeUnit.addItem("")
        self.comboBox_Order_TimeUnit.addItem("")
        self.comboBox_Order_TimeUnit.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_Order_TimeUnit, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_3, 0, 2, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.tableView_Order = QtWidgets.QTableView(self.tab)
        self.tableView_Order.setObjectName("tableView_Order")
        self.gridLayout_6.addWidget(self.tableView_Order, 0, 0, 3, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.comboBox_Orders_User = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_Orders_User.setObjectName("comboBox_Orders_User")
        self.comboBox_Orders_User.addItem("")
        self.comboBox_Orders_User.addItem("")
        self.gridLayout_5.addWidget(self.comboBox_Orders_User, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_4, 0, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_Orders_Teerace_jd = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_Orders_Teerace_jd.setChecked(True)
        self.checkBox_Orders_Teerace_jd.setObjectName("checkBox_Orders_Teerace_jd")
        self.gridLayout.addWidget(self.checkBox_Orders_Teerace_jd, 2, 0, 1, 1)
        self.checkBox_Orders_Teerace_pdd = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_Orders_Teerace_pdd.setChecked(True)
        self.checkBox_Orders_Teerace_pdd.setObjectName("checkBox_Orders_Teerace_pdd")
        self.gridLayout.addWidget(self.checkBox_Orders_Teerace_pdd, 3, 0, 1, 1)
        self.checkBox_Orders_Teerace_tb = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_Orders_Teerace_tb.setChecked(True)
        self.checkBox_Orders_Teerace_tb.setObjectName("checkBox_Orders_Teerace_tb")
        self.gridLayout.addWidget(self.checkBox_Orders_Teerace_tb, 1, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox, 1, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.checkBox_Orders_Type_wait = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_Orders_Type_wait.setChecked(True)
        self.checkBox_Orders_Type_wait.setObjectName("checkBox_Orders_Type_wait")
        self.gridLayout_3.addWidget(self.checkBox_Orders_Type_wait, 0, 0, 1, 1)
        self.checkBox_Orders_Type_succe = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_Orders_Type_succe.setObjectName("checkBox_Orders_Type_succe")
        self.gridLayout_3.addWidget(self.checkBox_Orders_Type_succe, 1, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_2, 2, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout_8.addWidget(self.tabWidget, 1, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menuFile.addAction(self.actionOpen)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.comboBox_Order_TimeStart.setCurrentIndex(1)
        self.comboBox_Order_TimeStop.setCurrentIndex(1)
        self.comboBox_Order_TimeUnit.setCurrentIndex(1)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_5.setTitle(_translate("MainWindow", "起始时间"))
        self.comboBox_Order_TimeStart.setItemText(0, _translate("MainWindow", "小时"))
        self.comboBox_Order_TimeStart.setItemText(1, _translate("MainWindow", "天"))
        self.comboBox_Order_TimeStart.setItemText(2, _translate("MainWindow", "周"))
        self.comboBox_Order_TimeStart.setItemText(3, _translate("MainWindow", "月"))
        self.groupBox_6.setTitle(_translate("MainWindow", "结束时间"))
        self.comboBox_Order_TimeStop.setItemText(0, _translate("MainWindow", "小时"))
        self.comboBox_Order_TimeStop.setItemText(1, _translate("MainWindow", "天"))
        self.comboBox_Order_TimeStop.setItemText(2, _translate("MainWindow", "周"))
        self.comboBox_Order_TimeStop.setItemText(3, _translate("MainWindow", "月"))
        self.groupBox_3.setTitle(_translate("MainWindow", "时间单位"))
        self.comboBox_Order_TimeUnit.setItemText(0, _translate("MainWindow", "小时"))
        self.comboBox_Order_TimeUnit.setItemText(1, _translate("MainWindow", "天"))
        self.comboBox_Order_TimeUnit.setItemText(2, _translate("MainWindow", "周"))
        self.comboBox_Order_TimeUnit.setItemText(3, _translate("MainWindow", "月"))
        self.groupBox_4.setTitle(_translate("MainWindow", "用户"))
        self.comboBox_Orders_User.setItemText(0, _translate("MainWindow", "用户订单"))
        self.comboBox_Orders_User.setItemText(1, _translate("MainWindow", "等待认领"))
        self.groupBox.setTitle(_translate("MainWindow", "订单平台"))
        self.checkBox_Orders_Teerace_jd.setText(_translate("MainWindow", "京东"))
        self.checkBox_Orders_Teerace_pdd.setText(_translate("MainWindow", "拼多多"))
        self.checkBox_Orders_Teerace_tb.setText(_translate("MainWindow", "淘宝"))
        self.groupBox_2.setTitle(_translate("MainWindow", "订单类型"))
        self.checkBox_Orders_Type_wait.setText(_translate("MainWindow", "等待收货"))
        self.checkBox_Orders_Type_succe.setText(_translate("MainWindow", "交易成功"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "用户订单"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "等待认领"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "提现记录"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))

