# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'orderDialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_OrderDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(949, 678)
        self.gridLayout_4 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.comboBox_Order_TimeUnit = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_Order_TimeUnit.setObjectName("comboBox_Order_TimeUnit")
        self.comboBox_Order_TimeUnit.addItem("")
        self.comboBox_Order_TimeUnit.addItem("")
        self.comboBox_Order_TimeUnit.addItem("")
        self.comboBox_Order_TimeUnit.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_Order_TimeUnit, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_Orders_Teerace_jd = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_Orders_Teerace_jd.setChecked(True)
        self.checkBox_Orders_Teerace_jd.setObjectName("checkBox_Orders_Teerace_jd")
        self.gridLayout.addWidget(self.checkBox_Orders_Teerace_jd, 2, 0, 1, 1)
        self.checkBox_Orders_Teerace_pdd = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_Orders_Teerace_pdd.setChecked(True)
        self.checkBox_Orders_Teerace_pdd.setObjectName("checkBox_Orders_Teerace_pdd")
        self.gridLayout.addWidget(self.checkBox_Orders_Teerace_pdd, 3, 0, 1, 1)
        self.checkBox_Orders_Teerace_tb = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_Orders_Teerace_tb.setChecked(True)
        self.checkBox_Orders_Teerace_tb.setObjectName("checkBox_Orders_Teerace_tb")
        self.gridLayout.addWidget(self.checkBox_Orders_Teerace_tb, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox, 0, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.checkBox_Orders_Type_wait = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_Orders_Type_wait.setChecked(True)
        self.checkBox_Orders_Type_wait.setObjectName("checkBox_Orders_Type_wait")
        self.gridLayout_3.addWidget(self.checkBox_Orders_Type_wait, 0, 0, 1, 1)
        self.checkBox_Orders_Type_succe = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_Orders_Type_succe.setObjectName("checkBox_Orders_Type_succe")
        self.gridLayout_3.addWidget(self.checkBox_Orders_Type_succe, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_2, 1, 1, 1, 1)
        self.tableView_Order = QtWidgets.QTableView(self.tab)
        self.tableView_Order.setObjectName("tableView_Order")
        self.gridLayout_5.addWidget(self.tableView_Order, 0, 0, 2, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.tableView_tixian = QtWidgets.QTableView(self.tab_3)
        self.tableView_tixian.setObjectName("tableView_tixian")
        self.gridLayout_9.addWidget(self.tableView_tixian, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout_4.addWidget(self.tabWidget, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.comboBox_Order_TimeUnit.setCurrentIndex(1)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox_3.setTitle(_translate("Dialog", "时间单位"))
        self.comboBox_Order_TimeUnit.setItemText(0, _translate("Dialog", "小时"))
        self.comboBox_Order_TimeUnit.setItemText(1, _translate("Dialog", "天"))
        self.comboBox_Order_TimeUnit.setItemText(2, _translate("Dialog", "周"))
        self.comboBox_Order_TimeUnit.setItemText(3, _translate("Dialog", "月"))
        self.groupBox.setTitle(_translate("Dialog", "订单平台"))
        self.checkBox_Orders_Teerace_jd.setText(_translate("Dialog", "京东"))
        self.checkBox_Orders_Teerace_pdd.setText(_translate("Dialog", "拼多多"))
        self.checkBox_Orders_Teerace_tb.setText(_translate("Dialog", "淘宝"))
        self.groupBox_2.setTitle(_translate("Dialog", "订单类型"))
        self.checkBox_Orders_Type_wait.setText(_translate("Dialog", "等待收货"))
        self.checkBox_Orders_Type_succe.setText(_translate("Dialog", "交易成功"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "用户订单"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "提现记录"))

