# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'orderDialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(949, 678)
        self.gridLayout_18 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.comboBox_Order_TimeUnit = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_Order_TimeUnit.setObjectName("comboBox_Order_TimeUnit")
        self.comboBox_Order_TimeUnit.addItem("")
        self.comboBox_Order_TimeUnit.addItem("")
        self.comboBox_Order_TimeUnit.addItem("")
        self.comboBox_Order_TimeUnit.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_Order_TimeUnit, 0, 0, 1, 1)
        self.gridLayout_18.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_Orders_Teerace_jd = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_Orders_Teerace_jd.setChecked(True)
        self.checkBox_Orders_Teerace_jd.setObjectName("checkBox_Orders_Teerace_jd")
        self.gridLayout.addWidget(self.checkBox_Orders_Teerace_jd, 2, 0, 1, 1)
        self.checkBox_Orders_Teerace_pdd = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_Orders_Teerace_pdd.setChecked(True)
        self.checkBox_Orders_Teerace_pdd.setObjectName("checkBox_Orders_Teerace_pdd")
        self.gridLayout.addWidget(self.checkBox_Orders_Teerace_pdd, 3, 0, 1, 1)
        self.checkBox_Orders_Teerace_tb = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_Orders_Teerace_tb.setChecked(True)
        self.checkBox_Orders_Teerace_tb.setObjectName("checkBox_Orders_Teerace_tb")
        self.gridLayout.addWidget(self.checkBox_Orders_Teerace_tb, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox, 0, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.checkBox_Orders_Type_wait = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_Orders_Type_wait.setChecked(True)
        self.checkBox_Orders_Type_wait.setObjectName("checkBox_Orders_Type_wait")
        self.gridLayout_3.addWidget(self.checkBox_Orders_Type_wait, 0, 0, 1, 1)
        self.checkBox_Orders_Type_succe = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_Orders_Type_succe.setObjectName("checkBox_Orders_Type_succe")
        self.gridLayout_3.addWidget(self.checkBox_Orders_Type_succe, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_2, 1, 1, 1, 1)
        self.tableView_Order = QtWidgets.QTableView(self.tab)
        self.tableView_Order.setObjectName("tableView_Order")
        self.gridLayout_5.addWidget(self.tableView_Order, 0, 0, 2, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.tableView_tixian = QtWidgets.QTableView(self.tab_3)
        self.tableView_tixian.setObjectName("tableView_tixian")
        self.gridLayout_9.addWidget(self.tableView_tixian, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.tableView_yongjing = QtWidgets.QTableView(self.tab_2)
        self.tableView_yongjing.setObjectName("tableView_yongjing")
        self.gridLayout_15.addWidget(self.tableView_yongjing, 0, 0, 2, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setMaximumSize(QtCore.QSize(275, 99999))
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label = QtWidgets.QLabel(self.groupBox_4)
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_yj_1 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_yj_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_yj_1.setObjectName("lineEdit_yj_1")
        self.gridLayout_6.addWidget(self.lineEdit_yj_1, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setObjectName("label_9")
        self.gridLayout_6.addWidget(self.label_9, 0, 2, 1, 1)
        self.lineEdit_bl_1 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_bl_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_bl_1.setObjectName("lineEdit_bl_1")
        self.gridLayout_6.addWidget(self.lineEdit_bl_1, 0, 3, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_4)
        self.label_17.setObjectName("label_17")
        self.gridLayout_6.addWidget(self.label_17, 0, 4, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_2.setObjectName("label_2")
        self.gridLayout_7.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEdit_yj_2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_yj_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_yj_2.setObjectName("lineEdit_yj_2")
        self.gridLayout_7.addWidget(self.lineEdit_yj_2, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        self.label_10.setObjectName("label_10")
        self.gridLayout_7.addWidget(self.label_10, 0, 2, 1, 1)
        self.lineEdit_bl_2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_bl_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_bl_2.setObjectName("lineEdit_bl_2")
        self.gridLayout_7.addWidget(self.lineEdit_bl_2, 0, 3, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_4)
        self.label_18.setObjectName("label_18")
        self.gridLayout_7.addWidget(self.label_18, 0, 4, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_7, 1, 0, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_3.setObjectName("label_3")
        self.gridLayout_8.addWidget(self.label_3, 0, 0, 1, 1)
        self.lineEdit_yj_3 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_yj_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_yj_3.setObjectName("lineEdit_yj_3")
        self.gridLayout_8.addWidget(self.lineEdit_yj_3, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_4)
        self.label_11.setObjectName("label_11")
        self.gridLayout_8.addWidget(self.label_11, 0, 2, 1, 1)
        self.lineEdit_bl_3 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_bl_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_bl_3.setObjectName("lineEdit_bl_3")
        self.gridLayout_8.addWidget(self.lineEdit_bl_3, 0, 3, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_4)
        self.label_19.setObjectName("label_19")
        self.gridLayout_8.addWidget(self.label_19, 0, 4, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_8, 2, 0, 1, 1)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setObjectName("label_4")
        self.gridLayout_10.addWidget(self.label_4, 0, 0, 1, 1)
        self.lineEdit_yj_4 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_yj_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_yj_4.setObjectName("lineEdit_yj_4")
        self.gridLayout_10.addWidget(self.lineEdit_yj_4, 0, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_4)
        self.label_12.setObjectName("label_12")
        self.gridLayout_10.addWidget(self.label_12, 0, 2, 1, 1)
        self.lineEdit_bl_4 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_bl_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_bl_4.setObjectName("lineEdit_bl_4")
        self.gridLayout_10.addWidget(self.lineEdit_bl_4, 0, 3, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_4)
        self.label_20.setObjectName("label_20")
        self.gridLayout_10.addWidget(self.label_20, 0, 4, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_10, 3, 0, 1, 1)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setObjectName("label_5")
        self.gridLayout_11.addWidget(self.label_5, 0, 0, 1, 1)
        self.lineEdit_yj_5 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_yj_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_yj_5.setObjectName("lineEdit_yj_5")
        self.gridLayout_11.addWidget(self.lineEdit_yj_5, 0, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_4)
        self.label_13.setObjectName("label_13")
        self.gridLayout_11.addWidget(self.label_13, 0, 2, 1, 1)
        self.lineEdit_bl_5 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_bl_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_bl_5.setObjectName("lineEdit_bl_5")
        self.gridLayout_11.addWidget(self.lineEdit_bl_5, 0, 3, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_4)
        self.label_21.setObjectName("label_21")
        self.gridLayout_11.addWidget(self.label_21, 0, 4, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_11, 4, 0, 1, 1)
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setObjectName("label_6")
        self.gridLayout_12.addWidget(self.label_6, 0, 0, 1, 1)
        self.lineEdit_yj_6 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_yj_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_yj_6.setObjectName("lineEdit_yj_6")
        self.gridLayout_12.addWidget(self.lineEdit_yj_6, 0, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_4)
        self.label_14.setObjectName("label_14")
        self.gridLayout_12.addWidget(self.label_14, 0, 2, 1, 1)
        self.lineEdit_bl_6 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_bl_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_bl_6.setObjectName("lineEdit_bl_6")
        self.gridLayout_12.addWidget(self.lineEdit_bl_6, 0, 3, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox_4)
        self.label_22.setObjectName("label_22")
        self.gridLayout_12.addWidget(self.label_22, 0, 4, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_12, 5, 0, 1, 1)
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setObjectName("label_7")
        self.gridLayout_13.addWidget(self.label_7, 0, 0, 1, 1)
        self.lineEdit_yj_7 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_yj_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_yj_7.setObjectName("lineEdit_yj_7")
        self.gridLayout_13.addWidget(self.lineEdit_yj_7, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_4)
        self.label_15.setObjectName("label_15")
        self.gridLayout_13.addWidget(self.label_15, 0, 2, 1, 1)
        self.lineEdit_bl_7 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_bl_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_bl_7.setObjectName("lineEdit_bl_7")
        self.gridLayout_13.addWidget(self.lineEdit_bl_7, 0, 3, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupBox_4)
        self.label_23.setObjectName("label_23")
        self.gridLayout_13.addWidget(self.label_23, 0, 4, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_13, 6, 0, 1, 1)
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setObjectName("label_8")
        self.gridLayout_14.addWidget(self.label_8, 0, 0, 1, 1)
        self.lineEdit_yj_8 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_yj_8.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_yj_8.setObjectName("lineEdit_yj_8")
        self.gridLayout_14.addWidget(self.lineEdit_yj_8, 0, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_4)
        self.label_16.setObjectName("label_16")
        self.gridLayout_14.addWidget(self.label_16, 0, 2, 1, 1)
        self.lineEdit_bl_8 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_bl_8.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_bl_8.setObjectName("lineEdit_bl_8")
        self.gridLayout_14.addWidget(self.lineEdit_bl_8, 0, 3, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox_4)
        self.label_24.setObjectName("label_24")
        self.gridLayout_14.addWidget(self.label_24, 0, 4, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_14, 7, 0, 1, 1)
        self.pushButton_calculate = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_calculate.setObjectName("pushButton_calculate")
        self.gridLayout_2.addWidget(self.pushButton_calculate, 8, 0, 1, 1)
        self.gridLayout_15.addWidget(self.groupBox_4, 0, 1, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_5.setMaximumSize(QtCore.QSize(275, 16777215))
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_25 = QtWidgets.QLabel(self.groupBox_5)
        self.label_25.setObjectName("label_25")
        self.gridLayout_16.addWidget(self.label_25, 0, 0, 1, 1)
        self.lineEdit_bl_9 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_bl_9.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_bl_9.setObjectName("lineEdit_bl_9")
        self.gridLayout_16.addWidget(self.lineEdit_bl_9, 0, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.groupBox_5)
        self.label_26.setObjectName("label_26")
        self.gridLayout_16.addWidget(self.label_26, 0, 2, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_16, 0, 0, 1, 1)
        self.gridLayout_15.addWidget(self.groupBox_5, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_18.addWidget(self.tabWidget, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.comboBox_Order_TimeUnit.setCurrentIndex(1)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox_3.setTitle(_translate("Dialog", "时间单位"))
        self.comboBox_Order_TimeUnit.setItemText(0, _translate("Dialog", "小时"))
        self.comboBox_Order_TimeUnit.setItemText(1, _translate("Dialog", "天"))
        self.comboBox_Order_TimeUnit.setItemText(2, _translate("Dialog", "周"))
        self.comboBox_Order_TimeUnit.setItemText(3, _translate("Dialog", "月"))
        self.groupBox.setTitle(_translate("Dialog", "订单平台"))
        self.checkBox_Orders_Teerace_jd.setText(_translate("Dialog", "京东"))
        self.checkBox_Orders_Teerace_pdd.setText(_translate("Dialog", "拼多多"))
        self.checkBox_Orders_Teerace_tb.setText(_translate("Dialog", "淘宝"))
        self.groupBox_2.setTitle(_translate("Dialog", "订单类型"))
        self.checkBox_Orders_Type_wait.setText(_translate("Dialog", "等待收货"))
        self.checkBox_Orders_Type_succe.setText(_translate("Dialog", "交易成功"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "用户订单"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "提现记录"))
        self.groupBox_4.setTitle(_translate("Dialog", "佣金比例"))
        self.label.setText(_translate("Dialog", "1.返利佣金≤"))
        self.lineEdit_yj_1.setText(_translate("Dialog", "3"))
        self.label_9.setText(_translate("Dialog", "元，分出总佣金"))
        self.lineEdit_bl_1.setText(_translate("Dialog", "75"))
        self.label_17.setText(_translate("Dialog", "%"))
        self.label_2.setText(_translate("Dialog", "2.返利佣金≤"))
        self.lineEdit_yj_2.setText(_translate("Dialog", "6"))
        self.label_10.setText(_translate("Dialog", "元，分出总佣金"))
        self.lineEdit_bl_2.setText(_translate("Dialog", "74"))
        self.label_18.setText(_translate("Dialog", "%"))
        self.label_3.setText(_translate("Dialog", "3.返利佣金≤"))
        self.lineEdit_yj_3.setText(_translate("Dialog", "10"))
        self.label_11.setText(_translate("Dialog", "元，分出总佣金"))
        self.lineEdit_bl_3.setText(_translate("Dialog", "73"))
        self.label_19.setText(_translate("Dialog", "%"))
        self.label_4.setText(_translate("Dialog", "4.返利佣金≤"))
        self.lineEdit_yj_4.setText(_translate("Dialog", "15"))
        self.label_12.setText(_translate("Dialog", "元，分出总佣金"))
        self.lineEdit_bl_4.setText(_translate("Dialog", "72"))
        self.label_20.setText(_translate("Dialog", "%"))
        self.label_5.setText(_translate("Dialog", "5.返利佣金≤"))
        self.lineEdit_yj_5.setText(_translate("Dialog", "25"))
        self.label_13.setText(_translate("Dialog", "元，分出总佣金"))
        self.lineEdit_bl_5.setText(_translate("Dialog", "71"))
        self.label_21.setText(_translate("Dialog", "%"))
        self.label_6.setText(_translate("Dialog", "6.返利佣金≤"))
        self.lineEdit_yj_6.setText(_translate("Dialog", "35"))
        self.label_14.setText(_translate("Dialog", "元，分出总佣金"))
        self.lineEdit_bl_6.setText(_translate("Dialog", "70"))
        self.label_22.setText(_translate("Dialog", "%"))
        self.label_7.setText(_translate("Dialog", "7.返利佣金≤"))
        self.lineEdit_yj_7.setText(_translate("Dialog", "50"))
        self.label_15.setText(_translate("Dialog", "元，分出总佣金"))
        self.lineEdit_bl_7.setText(_translate("Dialog", "69"))
        self.label_23.setText(_translate("Dialog", "%"))
        self.label_8.setText(_translate("Dialog", "8.返利佣金≤"))
        self.lineEdit_yj_8.setText(_translate("Dialog", "9999"))
        self.label_16.setText(_translate("Dialog", "元，分出总佣金"))
        self.lineEdit_bl_8.setText(_translate("Dialog", "68"))
        self.label_24.setText(_translate("Dialog", "%"))
        self.pushButton_calculate.setText(_translate("Dialog", "重新计算"))
        self.groupBox_5.setTitle(_translate("Dialog", "代理分成"))
        self.label_25.setText(_translate("Dialog", "一级代理"))
        self.lineEdit_bl_9.setText(_translate("Dialog", "6"))
        self.label_26.setText(_translate("Dialog", "%"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "佣金比例"))

